import express from 'express';
import { createServer as createViteServer } from 'vite';
import Database from 'better-sqlite3';
import nodemailer from 'nodemailer';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const db = new Database('exam.db');

// Initialize database
db.exec(`
  CREATE TABLE IF NOT EXISTS exams (
    id TEXT PRIMARY KEY,
    title TEXT,
    questions TEXT,
    solution_key TEXT,
    duration_minutes INTEGER,
    examiner_email TEXT
  );
  CREATE TABLE IF NOT EXISTS results (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    exam_id TEXT,
    student_name TEXT,
    student_class TEXT,
    responses TEXT,
    score INTEGER,
    total_marks INTEGER,
    terminated BOOLEAN,
    timestamp DATETIME DEFAULT CURRENT_TIMESTAMP
  );
`);

async function startServer() {
  const app = express();
  app.use(express.json());
  const PORT = 3000;

  // API Routes
  app.post('/api/exams', (req, res) => {
    const { id, title, questions, solutionKey, durationMinutes, examinerEmail } = req.body;
    const stmt = db.prepare('INSERT OR REPLACE INTO exams (id, title, questions, solution_key, duration_minutes, examiner_email) VALUES (?, ?, ?, ?, ?, ?)');
    stmt.run(id, title, JSON.stringify(questions), JSON.stringify(solutionKey), durationMinutes, examinerEmail);
    res.json({ success: true });
  });

  app.get('/api/exams/:id', (req, res) => {
    const stmt = db.prepare('SELECT * FROM exams WHERE id = ?');
    const exam = stmt.get(req.params.id) as any;
    if (!exam) return res.status(404).json({ error: 'Exam not found' });
    
    res.json({
      id: exam.id,
      title: exam.title,
      questions: JSON.parse(exam.questions),
      durationMinutes: exam.duration_minutes,
      examinerEmail: exam.examiner_email
    });
  });

  app.post('/api/submit', async (req, res) => {
    const { examId, studentName, studentClass, responses, terminated } = req.body;
    
    const examStmt = db.prepare('SELECT * FROM exams WHERE id = ?');
    const exam = examStmt.get(examId) as any;
    if (!exam) return res.status(404).json({ error: 'Exam not found' });

    const solutionKey = JSON.parse(exam.solution_key);
    const questions = JSON.parse(exam.questions);
    const examinerEmail = exam.examiner_email;
    
    let score = 0;
    questions.forEach((q: any) => {
      if (responses[q.id] === solutionKey[q.id]) {
        score++;
      }
    });

    const totalMarks = questions.length;
    const percentage = Math.round((score / totalMarks) * 100);
    const passThreshold = 40;
    const resultStatus = percentage >= passThreshold ? 'PASS' : 'FAIL';

    const responseDetails = questions.map((q: any) => {
      const studentAnsIdx = responses[q.id];
      const studentAnsText = studentAnsIdx !== undefined ? q.options[studentAnsIdx] : 'Not Answered';
      const correctAnsIdx = solutionKey[q.id];
      const correctAnsText = q.options[correctAnsIdx];
      const isCorrect = studentAnsIdx === correctAnsIdx;
      return `Question: ${q.text}\nStudent Answer: ${studentAnsText}\nCorrect Answer: ${correctAnsText}\nResult: ${isCorrect ? 'CORRECT' : 'INCORRECT'}`;
    }).join('\n\n---\n\n');

    const resultStmt = db.prepare(`
      INSERT INTO results (exam_id, student_name, student_class, responses, score, total_marks, terminated)
      VALUES (?, ?, ?, ?, ?, ?, ?)
    `);
    resultStmt.run(examId, studentName, studentClass, JSON.stringify(responses), score, totalMarks, terminated ? 1 : 0);

    // Send email to examiner
    if (process.env.SMTP_HOST) {
      try {
        const transporter = nodemailer.createTransport({
          host: process.env.SMTP_HOST,
          port: Number(process.env.SMTP_PORT || 587),
          secure: process.env.SMTP_SECURE === 'true',
          auth: {
            user: process.env.SMTP_USER,
            pass: process.env.SMTP_PASS,
          },
        });

        const mailOptions = {
          from: process.env.SMTP_USER,
          to: examinerEmail || process.env.EXAMINER_EMAIL,
          subject: `Exam Result: ${studentName} - ${exam.title} [${resultStatus}]`,
          text: `
SECURE EXAM SYSTEM - RESULT REPORT
==================================

STUDENT INFORMATION
-------------------
Name: ${studentName}
Class: ${studentClass}
Exam: ${exam.title}

PERFORMANCE SUMMARY
-------------------
Score: ${score} / ${totalMarks}
Percentage: ${percentage}%
Result Status: ${resultStatus}
Status: ${terminated ? 'TERMINATED (Security Violation)' : 'Successfully Submitted'}

DETAILED RESPONSES
------------------
${responseDetails}

==================================
Generated by Secure Exam System
`,
        };

        await transporter.sendMail(mailOptions);
      } catch (error) {
        console.error('Failed to send email:', error);
      }
    } else {
      console.warn('SMTP_HOST not configured. Skipping email delivery.');
    }

    res.json({ score, totalMarks, success: true, resultStatus, solutionKey });
  });

  // Vite middleware for development
  if (process.env.NODE_ENV !== 'production') {
    const vite = await createViteServer({
      server: { middlewareMode: true },
      appType: 'spa',
    });
    app.use(vite.middlewares);
  } else {
    app.use(express.static(path.join(__dirname, 'dist')));
    app.get('*', (req, res) => {
      res.sendFile(path.join(__dirname, 'dist', 'index.html'));
    });
  }

  app.listen(PORT, '0.0.0.0', () => {
    console.log(`Server running on http://localhost:${PORT}`);
  });
}

startServer();
